name: testreport
version: 1.3.0-dev
homepage: https://github.com/TOPdesk/dart-testreport
description: >
  This library can be used to process the results of dart tests.
  It processes data from the `json` output emitted by the dart test runner
  and provide an API to the test results.

dev_dependencies:
  test: any

environment:
  sdk: ">=3.0.0 <4.0.0"
